name: Update Data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */1 * * *'

concurrency: ci-${{ github.ref }}

jobs:
  main:
    name: Update Data
    runs-on: ubuntu-24.04

    env:
      PATH_EXPORTER: backlog
      PATH_DATA: backlog/backlog_data

    steps:
      - name: Checkout export tool repository
        uses: actions/checkout@v4
        with:
          repository: peolic/stashdb_backlog_export
          path: ${{ env.PATH_EXPORTER }}

      - name: Checkout data repository
        uses: actions/checkout@v4
        with:
          path: ${{ env.PATH_DATA }}

      # - name: Set up Python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: '3.11'

      - name: Install dependencies
        working-directory: ${{ env.PATH_EXPORTER }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate new data
        working-directory: ${{ env.PATH_EXPORTER }}
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: |
          python make_backlog_data.py

      - name: Check for changes
        working-directory: ${{ env.PATH_DATA }}
        run: |
          git add --intent-to-add .
          if git diff HEAD --stat --exit-code; then
            echo "changes_exist=false" >> $GITHUB_ENV
          else
            echo "changes_exist=true" >> $GITHUB_ENV
          fi

          echo "current_cache=$(git ls-remote origin refs/tags/cache --exit-code | cut -d $'\t' -f1)" >> $GITHUB_ENV
          echo "TIMESTAMP=$(date +'%Y-%m-%d %H:%M:%S %Z')" >> $GITHUB_ENV

      - name: Commit files
        if: ${{ env.changes_exist == 'true' }}
        working-directory: ${{ env.PATH_DATA }}
        env:
          GIT_AUTHOR_NAME: peolic
          GIT_AUTHOR_EMAIL: 66393006+peolic@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
        run: |
          git add -A
          git commit -m "update data"
          git push

      - name: Push tag
        if: ${{ env.changes_exist == 'true' || env.current_cache != github.sha }}
        working-directory: ${{ env.PATH_DATA }}
        run: |
          git push origin HEAD:refs/tags/cache -f

      - name: Release cache data
        uses: softprops/action-gh-release@v2
        if: ${{ env.changes_exist == 'true' || env.current_cache != github.sha }}
        with:
          name: Cache
          tag_name: cache
          target_commitish: main
          prerelease: true
          body: "All the data in cache format.\n\nUpdated: **${{ env.TIMESTAMP }}**"
          fail_on_unmatched_files: true
          files: ${{ env.PATH_EXPORTER }}/stashdb_backlog.json
          token: ${{ secrets.GITHUB_TOKEN }}
