name: Update Data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *'

jobs:
  main:
    name: Update Data
    runs-on: ubuntu-latest

    env:
      PATH_TOOLS: backlog
      PATH_DATA: backlog/backlog_data

    steps:
      - name: Checkout tools repository
        uses: actions/checkout@v2
        with:
          repository: peolic/stashdb_backlog
          token: ${{ secrets.TOKEN }}
          path: ${{ env.PATH_TOOLS }}

      - name: Checkout data repository
        uses: actions/checkout@v2
        with:
          path: ${{ env.PATH_DATA }}

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        working-directory: ${{ env.PATH_TOOLS }}
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 cssutils requests

      - name: Generate new data
        working-directory: ${{ env.PATH_TOOLS }}
        run: |
          python make_backlog_data.py
          mv .stashdb_backlog_index.json stashdb_backlog_index.json
          mv .stashdb_backlog.json stashdb_backlog.json

      - name: Check for changes
        working-directory: ${{ env.PATH_DATA }}
        run: |
          git add --intent-to-add .
          if git diff --stat --exit-code; then
            echo "changes_exist=false" >> $GITHUB_ENV
          else
            echo "changes_exist=true" >> $GITHUB_ENV
          fi

      - name: Commit files
        if: ${{ env.changes_exist == 'true' }}
        working-directory: ${{ env.PATH_DATA }}
        env:
          GIT_AUTHOR_NAME: peolic
          GIT_AUTHOR_EMAIL: 66393006+peolic@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
        run: |
          git add -A
          git commit -m "update data"

      - name: Push changes
        uses: ad-m/github-push-action@master
        if: ${{ env.changes_exist == 'true' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          directory: ${{ env.PATH_DATA }}

      - name: Push tag
        if: ${{ env.changes_exist == 'true' }}
        working-directory: ${{ env.PATH_DATA }}
        run: |
          git push origin HEAD:refs/tags/cache -f

      - name: Release cache data
        uses: softprops/action-gh-release@v1
        if: ${{ env.changes_exist == 'true' }}
        with:
          name: Cache
          tag_name: cache
          target_commitish: main
          prerelease: true
          # body: "All the data in cache format."
          fail_on_unmatched_files: true
          files: |
            ${{ env.PATH_TOOLS }}/stashdb_backlog_index.json
            ${{ env.PATH_TOOLS }}/stashdb_backlog.json
          token: ${{ secrets.GITHUB_TOKEN }}
