name: Pack Data

on:
  workflow_dispatch:

jobs:
  main:
    name: Pack Data
    runs-on: ubuntu-24.04

    env:
      PATH_EXPORTER: backlog
      PATH_DATA: backlog/backlog_data

    steps:
      - name: Checkout export tool repository
        uses: actions/checkout@v4
        with:
          repository: peolic/stashdb_backlog_export
          path: ${{ env.PATH_EXPORTER }}

      - name: Checkout data repository
        uses: actions/checkout@v4
        with:
          path: ${{ env.PATH_DATA }}

      # - name: Set up Python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: '3.11'

      - name: Install dependencies
        working-directory: ${{ env.PATH_EXPORTER }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Pack data
        working-directory: ${{ env.PATH_EXPORTER }}
        run: |
          python pack_backlog_data.py

      - name: Check for changes
        working-directory: ${{ env.PATH_DATA }}
        run: |
          echo "current_cache=$(git ls-remote origin refs/tags/cache --exit-code | cut -d $'\t' -f1)" >> $GITHUB_ENV
          echo "TIMESTAMP=$(date +'%Y-%m-%d %H:%M:%S %Z')" >> $GITHUB_ENV

      - name: Push tag
        if: ${{ env.current_cache != github.sha }}
        working-directory: ${{ env.PATH_DATA }}
        run: |
          git push origin HEAD:refs/tags/cache -f

      - name: Release cache data
        # uses: softprops/action-gh-release@v1
        # waiting on official release
        uses: softprops/action-gh-release@4634c16e79c963813287e889244c50009e7f0981
        if: ${{ env.current_cache != github.sha }}
        with:
          name: Cache
          tag_name: cache
          target_commitish: main
          prerelease: true
          body: "All the data in cache format.\n\nUpdated: **${{ env.TIMESTAMP }}**"
          fail_on_unmatched_files: true
          files: ${{ env.PATH_EXPORTER }}/stashdb_backlog.json
          token: ${{ secrets.GITHUB_TOKEN }}
